// const
export const GET_DEFAULT_LIST_PENDING = 'GET_DEFAULT_LIST_PENDING'
export const GET_DEFAULT_LIST_FULFILLED = 'GET_DEFAULT_LIST_FULFILLED'
export const GET_DEFAULT_LIST_REJECTED = 'GET_DEFAULT_LIST_REJECTED'
export const REMOVE_ITEM_FROM_LIST = 'REMOVE_ITEM_FROM_LIST'
export const UPDATE_ITEM_FROM_LIST = 'UPDATE_ITEM_FROM_LIST'
export const UPDATE_ITEM_FROM_LIST_REJECTED = 'UPDATE_ITEM_FROM_LIST_REJECTED'
export const UPDATING_ITEM_FROM_LIST = 'UPDATING_ITEM_FROM_LIST'
export const ADD_NEW_ITEM_TO_LIST = 'ADD_NEW_ITEM_TO_LIST'
export const ADDING_NEW_ITEM_TO_LIST = 'ADDING_NEW_ITEM_TO_LIST'
export const ADD_NEW_ITEM_TO_LIST_REJECTED = 'ADD_NEW_ITEM_TO_LIST_REJECTED'
export const SET_UPDATING_ITEM = 'SET_UPDATING_ITEM'



